-- Seed canonical dish categories so the menu-scan AI has a rich taxonomy to choose from.
-- Categories are admin-editable; this is just a starting baseline.
-- ON CONFLICT (name) DO NOTHING so re-running this migration is safe.

INSERT INTO public.dish_categories (name, is_drink, is_active) VALUES
  -- Pizza & flatbreads
  ('Pizza', false, true),
  ('Calzone', false, true),
  ('Stromboli', false, true),
  ('Focaccia', false, true),
  ('Flatbread', false, true),
  ('Pinsa', false, true),
  ('Pide', false, true),
  ('Lahmacun', false, true),
  ('Manakish', false, true),
  ('Socca', false, true),

  -- Burgers & sandwiches
  ('Burger', false, true),
  ('Cheeseburger', false, true),
  ('Slider', false, true),
  ('Veggie Burger', false, true),
  ('Sandwich', false, true),
  ('Club Sandwich', false, true),
  ('Panini', false, true),
  ('Grilled Cheese', false, true),
  ('Reuben', false, true),
  ('BLT', false, true),
  ('Sub', false, true),
  ('Hoagie', false, true),
  ('Po Boy', false, true),
  ('Philly Cheesesteak', false, true),
  ('Lobster Roll', false, true),
  ('Wrap', false, true),
  ('Bánh Mì', false, true),
  ('Cubano', false, true),
  ('Torta', false, true),
  ('Cemita', false, true),
  ('Hot Dog', false, true),
  ('Corn Dog', false, true),
  ('Bratwurst Plate', false, true),
  ('Sausage Plate', false, true),

  -- Mexican / Latin American
  ('Taco', false, true),
  ('Burrito', false, true),
  ('Quesadilla', false, true),
  ('Enchilada', false, true),
  ('Tostada', false, true),
  ('Sope', false, true),
  ('Flauta', false, true),
  ('Chalupa', false, true),
  ('Gordita', false, true),
  ('Mulita', false, true),
  ('Memela', false, true),
  ('Tlacoyo', false, true),
  ('Tlayuda', false, true),
  ('Chimichanga', false, true),
  ('Fajita', false, true),
  ('Nachos', false, true),
  ('Chile Relleno', false, true),
  ('Tamale', false, true),
  ('Mole', false, true),
  ('Pozole', false, true),
  ('Birria', false, true),
  ('Cochinita Pibil', false, true),
  ('Carnitas', false, true),
  ('Al Pastor', false, true),
  ('Carne Asada', false, true),
  ('Barbacoa', false, true),
  ('Ceviche', false, true),
  ('Aguachile', false, true),
  ('Esquite', false, true),
  ('Elote', false, true),
  ('Empanada', false, true),
  ('Arepa', false, true),
  ('Pupusa', false, true),
  ('Mofongo', false, true),
  ('Lomo Saltado', false, true),
  ('Aji de Gallina', false, true),
  ('Anticucho', false, true),
  ('Picanha', false, true),
  ('Churrasco', false, true),
  ('Asado', false, true),
  ('Feijoada', false, true),
  ('Moqueca', false, true),
  ('Picadillo', false, true),

  -- Italian
  ('Pasta', false, true),
  ('Spaghetti', false, true),
  ('Lasagna', false, true),
  ('Ravioli', false, true),
  ('Tortellini', false, true),
  ('Gnocchi', false, true),
  ('Cannelloni', false, true),
  ('Carbonara', false, true),
  ('Cacio e Pepe', false, true),
  ('Pesto Pasta', false, true),
  ('Bolognese', false, true),
  ('Fettuccine Alfredo', false, true),
  ('Risotto', false, true),
  ('Pasta Primavera', false, true),
  ('Antipasti', false, true),
  ('Bruschetta', false, true),
  ('Crostini', false, true),
  ('Caprese Salad', false, true),
  ('Caponata', false, true),
  ('Polenta', false, true),
  ('Saltimbocca', false, true),
  ('Osso Buco', false, true),
  ('Arancini', false, true),
  ('Suppli', false, true),

  -- French
  ('Croque Monsieur', false, true),
  ('Crêpe', false, true),
  ('Quiche', false, true),
  ('Coq au Vin', false, true),
  ('Beef Bourguignon', false, true),
  ('Ratatouille', false, true),
  ('Cassoulet', false, true),
  ('Bouillabaisse', false, true),
  ('Confit', false, true),
  ('Foie Gras', false, true),
  ('Steak Frites', false, true),
  ('Soufflé', false, true),

  -- Spanish
  ('Tapas', false, true),
  ('Paella', false, true),
  ('Tortilla Española', false, true),
  ('Patatas Bravas', false, true),
  ('Croquetas', false, true),
  ('Gambas al Ajillo', false, true),
  ('Jamón Plate', false, true),

  -- Eastern European
  ('Pierogi', false, true),
  ('Borscht', false, true),
  ('Goulash', false, true),
  ('Schnitzel', false, true),
  ('Cabbage Rolls', false, true),
  ('Pelmeni', false, true),
  ('Vareniki', false, true),
  ('Bigos', false, true),
  ('Spätzle', false, true),
  ('Pretzel', false, true),
  ('Currywurst', false, true),

  -- Japanese
  ('Sushi', false, true),
  ('Nigiri', false, true),
  ('Sashimi', false, true),
  ('Maki Roll', false, true),
  ('Temaki', false, true),
  ('Chirashi', false, true),
  ('Tempura', false, true),
  ('Donburi', false, true),
  ('Ramen', false, true),
  ('Udon', false, true),
  ('Soba', false, true),
  ('Yakisoba', false, true),
  ('Yakitori', false, true),
  ('Teppanyaki', false, true),
  ('Teriyaki', false, true),
  ('Tonkatsu', false, true),
  ('Karaage', false, true),
  ('Gyoza', false, true),
  ('Takoyaki', false, true),
  ('Okonomiyaki', false, true),
  ('Onigiri', false, true),
  ('Bento', false, true),
  ('Sukiyaki', false, true),
  ('Shabu Shabu', false, true),
  ('Mochi', false, true),
  ('Dorayaki', false, true),
  ('Taiyaki', false, true),

  -- Chinese
  ('Dim Sum', false, true),
  ('Dumplings', false, true),
  ('Bao Buns', false, true),
  ('Xiao Long Bao', false, true),
  ('Char Siu Bao', false, true),
  ('Wontons', false, true),
  ('Spring Rolls', false, true),
  ('Egg Rolls', false, true),
  ('Potstickers', false, true),
  ('Lo Mein', false, true),
  ('Chow Mein', false, true),
  ('Chow Fun', false, true),
  ('Dan Dan Noodles', false, true),
  ('Mapo Tofu', false, true),
  ('Kung Pao Chicken', false, true),
  ('General Tso Chicken', false, true),
  ('Orange Chicken', false, true),
  ('Sweet and Sour Chicken', false, true),
  ('Cashew Chicken', false, true),
  ('Beef and Broccoli', false, true),
  ('Mongolian Beef', false, true),
  ('Peking Duck', false, true),
  ('Hainanese Chicken', false, true),
  ('Hot Pot', false, true),
  ('Congee', false, true),
  ('Fried Rice', false, true),

  -- Korean
  ('Bibimbap', false, true),
  ('Bulgogi', false, true),
  ('Korean BBQ', false, true),
  ('Galbi', false, true),
  ('Japchae', false, true),
  ('Jjajangmyeon', false, true),
  ('Tteokbokki', false, true),
  ('Korean Fried Chicken', false, true),
  ('Mandu', false, true),
  ('Banchan', false, true),
  ('Kimchi Stew', false, true),
  ('Sundubu', false, true),

  -- Thai
  ('Pad Thai', false, true),
  ('Pad See Ew', false, true),
  ('Pad Kra Pao', false, true),
  ('Tom Yum', false, true),
  ('Tom Kha', false, true),
  ('Thai Green Curry', false, true),
  ('Thai Red Curry', false, true),
  ('Massaman Curry', false, true),
  ('Panang Curry', false, true),
  ('Larb', false, true),
  ('Som Tum', false, true),

  -- Vietnamese
  ('Pho', false, true),
  ('Bún', false, true),
  ('Bún Chả', false, true),
  ('Hủ Tiếu', false, true),
  ('Chả Giò', false, true),
  ('Gỏi Cuốn', false, true),
  ('Cơm Tấm', false, true),

  -- Indian / South Asian
  ('Curry', false, true),
  ('Tikka Masala', false, true),
  ('Butter Chicken', false, true),
  ('Vindaloo', false, true),
  ('Korma', false, true),
  ('Saag', false, true),
  ('Biryani', false, true),
  ('Naan', false, true),
  ('Tandoori', false, true),
  ('Samosa', false, true),
  ('Pakora', false, true),
  ('Dal', false, true),
  ('Chana Masala', false, true),
  ('Aloo Gobi', false, true),
  ('Paneer Tikka', false, true),
  ('Palak Paneer', false, true),
  ('Dosa', false, true),
  ('Idli', false, true),
  ('Uttapam', false, true),
  ('Pav Bhaji', false, true),
  ('Chaat', false, true),
  ('Rogan Josh', false, true),
  ('Chole Bhature', false, true),
  ('Gulab Jamun', false, true),
  ('Jalebi', false, true),
  ('Kulfi', false, true),

  -- Southeast Asian
  ('Nasi Goreng', false, true),
  ('Nasi Lemak', false, true),
  ('Mee Goreng', false, true),
  ('Laksa', false, true),
  ('Satay', false, true),
  ('Rendang', false, true),
  ('Adobo', false, true),
  ('Lumpia', false, true),
  ('Sinigang', false, true),
  ('Lechon', false, true),

  -- Middle Eastern / Mediterranean
  ('Kebab', false, true),
  ('Shish Kebab', false, true),
  ('Kofta', false, true),
  ('Adana Kebab', false, true),
  ('Shawarma', false, true),
  ('Gyro', false, true),
  ('Doner', false, true),
  ('Falafel', false, true),
  ('Hummus', false, true),
  ('Baba Ganoush', false, true),
  ('Tabbouleh', false, true),
  ('Fattoush', false, true),
  ('Mezze', false, true),
  ('Dolma', false, true),
  ('Maqluba', false, true),
  ('Kibbeh', false, true),
  ('Mansaf', false, true),
  ('Souvlaki', false, true),
  ('Moussaka', false, true),
  ('Spanakopita', false, true),
  ('Tzatziki', false, true),
  ('Greek Salad', false, true),
  ('Baklava', false, true),
  ('Kunefe', false, true),
  ('Halva', false, true),

  -- African
  ('Tagine', false, true),
  ('Couscous', false, true),
  ('Harira', false, true),
  ('Shakshuka', false, true),
  ('Injera with Wat', false, true),
  ('Tibs', false, true),
  ('Jollof Rice', false, true),
  ('Suya', false, true),

  -- Caribbean
  ('Jerk Chicken', false, true),
  ('Roti', false, true),

  -- Soups & Stews
  ('Soup', false, true),
  ('Stew', false, true),
  ('Chowder', false, true),
  ('Bisque', false, true),
  ('Chili', false, true),
  ('Minestrone', false, true),
  ('French Onion Soup', false, true),
  ('Clam Chowder', false, true),
  ('Chicken Noodle Soup', false, true),
  ('Matzo Ball Soup', false, true),
  ('Miso Soup', false, true),
  ('Hot and Sour Soup', false, true),
  ('Egg Drop Soup', false, true),
  ('Wonton Soup', false, true),
  ('Gumbo', false, true),
  ('Jambalaya', false, true),

  -- Salads
  ('Salad', false, true),
  ('Caesar Salad', false, true),
  ('Cobb Salad', false, true),
  ('Waldorf Salad', false, true),
  ('Niçoise Salad', false, true),
  ('Wedge Salad', false, true),
  ('Kale Salad', false, true),
  ('Quinoa Salad', false, true),
  ('Chopped Salad', false, true),
  ('Pasta Salad', false, true),
  ('Potato Salad', false, true),
  ('Coleslaw', false, true),

  -- Bowls
  ('Bowl', false, true),
  ('Rice Bowl', false, true),
  ('Poke Bowl', false, true),
  ('Burrito Bowl', false, true),
  ('Buddha Bowl', false, true),
  ('Grain Bowl', false, true),
  ('Acai Bowl', false, true),
  ('Smoothie Bowl', false, true),

  -- Steak / BBQ / Grill
  ('Steak', false, true),
  ('Tomahawk Steak', false, true),
  ('BBQ Ribs', false, true),
  ('Brisket', false, true),
  ('Pulled Pork', false, true),
  ('Pulled Chicken', false, true),
  ('Smoked Meat', false, true),
  ('Lamb Chop', false, true),
  ('Pork Chop', false, true),
  ('Veal Chop', false, true),
  ('Mixed Grill', false, true),

  -- Poultry
  ('Chicken', false, true),
  ('Fried Chicken', false, true),
  ('Roast Chicken', false, true),
  ('Grilled Chicken', false, true),
  ('Chicken Wings', false, true),
  ('Chicken Tenders', false, true),
  ('Chicken Parmesan', false, true),
  ('Chicken Marsala', false, true),
  ('Chicken Cacciatore', false, true),
  ('Pollo Asado', false, true),
  ('Duck', false, true),
  ('Turkey', false, true),
  ('Quail', false, true),

  -- Seafood
  ('Seafood Platter', false, true),
  ('Fish', false, true),
  ('Grilled Fish', false, true),
  ('Fried Fish', false, true),
  ('Salmon', false, true),
  ('Tuna', false, true),
  ('Cod', false, true),
  ('Halibut', false, true),
  ('Sea Bass', false, true),
  ('Tilapia', false, true),
  ('Trout', false, true),
  ('Snapper', false, true),
  ('Swordfish', false, true),
  ('Mahi Mahi', false, true),
  ('Oysters', false, true),
  ('Clams', false, true),
  ('Mussels', false, true),
  ('Scallops', false, true),
  ('Shrimp', false, true),
  ('Prawn', false, true),
  ('Lobster', false, true),
  ('Crab', false, true),
  ('Crab Cake', false, true),
  ('Calamari', false, true),
  ('Octopus', false, true),
  ('Crudo', false, true),
  ('Tartare', false, true),
  ('Carpaccio', false, true),
  ('Fish and Chips', false, true),
  ('Fish Tacos', false, true),
  ('Cioppino', false, true),

  -- Vegetarian / Vegan headliners
  ('Vegan Bowl', false, true),
  ('Vegetable Curry', false, true),
  ('Stuffed Peppers', false, true),
  ('Stuffed Mushrooms', false, true),
  ('Eggplant Parmesan', false, true),
  ('Tofu Dish', false, true),
  ('Tempeh Dish', false, true),

  -- Breakfast & Brunch
  ('Breakfast', false, true),
  ('Brunch', false, true),
  ('Eggs Benedict', false, true),
  ('Omelette', false, true),
  ('Frittata', false, true),
  ('Scrambled Eggs', false, true),
  ('Huevos Rancheros', false, true),
  ('Chilaquiles', false, true),
  ('Migas', false, true),
  ('Avocado Toast', false, true),
  ('French Toast', false, true),
  ('Pancakes', false, true),
  ('Waffles', false, true),
  ('Granola', false, true),
  ('Oatmeal', false, true),
  ('Porridge', false, true),
  ('Yogurt Parfait', false, true),
  ('Bagel and Lox', false, true),
  ('Breakfast Burrito', false, true),
  ('Breakfast Sandwich', false, true),
  ('Full English', false, true),

  -- Sides & starters
  ('Appetizer', false, true),
  ('Side Dish', false, true),
  ('Fries', false, true),
  ('Sweet Potato Fries', false, true),
  ('Poutine', false, true),
  ('Onion Rings', false, true),
  ('Mozzarella Sticks', false, true),
  ('Jalapeño Poppers', false, true),
  ('Loaded Nachos', false, true),
  ('Guacamole', false, true),
  ('Salsa', false, true),
  ('Queso Dip', false, true),
  ('Spinach Artichoke Dip', false, true),
  ('Garlic Bread', false, true),
  ('Breadsticks', false, true),
  ('Hush Puppies', false, true),
  ('Cornbread', false, true),
  ('Biscuits', false, true),
  ('Hash Browns', false, true),
  ('Tater Tots', false, true),
  ('Mashed Potatoes', false, true),
  ('Roasted Vegetables', false, true),
  ('Grilled Vegetables', false, true),
  ('Plantains', false, true),
  ('Tostones', false, true),
  ('Pickled Vegetables', false, true),
  ('Croquette', false, true),
  ('Polpette', false, true),

  -- Desserts
  ('Dessert', false, true),
  ('Cake', false, true),
  ('Cheesecake', false, true),
  ('Tiramisu', false, true),
  ('Panna Cotta', false, true),
  ('Crème Brûlée', false, true),
  ('Flan', false, true),
  ('Tres Leches', false, true),
  ('Mousse', false, true),
  ('Pudding', false, true),
  ('Brownie', false, true),
  ('Cookie', false, true),
  ('Pie', false, true),
  ('Tart', false, true),
  ('Cobbler', false, true),
  ('Crumble', false, true),
  ('Churros', false, true),
  ('Ice Cream', false, true),
  ('Sorbet', false, true),
  ('Frozen Yogurt', false, true),
  ('Sundae', false, true),
  ('Banana Split', false, true),
  ('Tarte Tatin', false, true),
  ('Macaron', false, true),
  ('Éclair', false, true),
  ('Mille-feuille', false, true),
  ('Cannoli', false, true),
  ('Gelato', false, true),
  ('Rice Pudding', false, true),
  ('Bread Pudding', false, true),
  ('Sticky Toffee Pudding', false, true),
  ('Banoffee Pie', false, true),
  ('Key Lime Pie', false, true),
  ('Pecan Pie', false, true),
  ('Apple Pie', false, true),

  -- Pizza-specific styles
  ('Margherita Pizza', false, true),
  ('Pepperoni Pizza', false, true),
  ('Hawaiian Pizza', false, true),
  ('White Pizza', false, true),
  ('Detroit-Style Pizza', false, true),
  ('Sicilian Pizza', false, true),
  ('Chicago Deep Dish', false, true),
  ('Neapolitan Pizza', false, true),
  ('Quattro Formaggi', false, true),
  ('Diavola Pizza', false, true),

  -- Pasta-specific
  ('Penne', false, true),
  ('Pappardelle', false, true),
  ('Tagliatelle', false, true),
  ('Orecchiette', false, true),
  ('Trofie', false, true),
  ('Linguine', false, true),
  ('Bucatini', false, true),
  ('Pasta al Forno', false, true),
  ('Pasta alla Norma', false, true),
  ('Pasta Vongole', false, true),
  ('Pasta Puttanesca', false, true),
  ('Pasta Amatriciana', false, true),
  ('Aglio e Olio', false, true),
  ('Manicotti', false, true),

  -- Sushi rolls / Japanese specifics
  ('California Roll', false, true),
  ('Spicy Tuna Roll', false, true),
  ('Rainbow Roll', false, true),
  ('Dragon Roll', false, true),
  ('Volcano Roll', false, true),
  ('Hand Roll', false, true),
  ('Negimaki', false, true),
  ('Hambagu Steak', false, true),
  ('Omurice', false, true),
  ('Saba', false, true),
  ('Unadon', false, true),
  ('Yakimeshi', false, true),
  ('Katsu Curry', false, true),
  ('Curry Don', false, true),

  -- Chinese specifics
  ('Twice Cooked Pork', false, true),
  ('Bang Bang Chicken', false, true),
  ('Drunken Chicken', false, true),
  ('Lions Head Meatballs', false, true),
  ('Sichuan Boiled Fish', false, true),
  ('Cantonese Roast Duck', false, true),
  ('Xinjiang Lamb', false, true),
  ('Wood Ear Salad', false, true),
  ('Char Siu', false, true),
  ('Salt and Pepper Squid', false, true),
  ('Sweet and Sour Pork', false, true),
  ('Dumpling Soup', false, true),
  ('Scallion Pancake', false, true),

  -- Korean specifics
  ('Yukgaejang', false, true),
  ('Kimbap', false, true),
  ('Hotteok', false, true),
  ('Naengmyeon', false, true),
  ('Soondae', false, true),
  ('Dakgalbi', false, true),
  ('Gamjatang', false, true),
  ('Budae Jjigae', false, true),
  ('Doenjang Jjigae', false, true),

  -- Thai specifics
  ('Khao Soi', false, true),
  ('Khao Pad', false, true),
  ('Khao Man Gai', false, true),
  ('Pla Pao', false, true),
  ('Yam Salad', false, true),
  ('Mango Sticky Rice', false, true),
  ('Roti Sai Mai', false, true),

  -- Vietnamese specifics
  ('Bun Bo Hue', false, true),
  ('Bun Rieu', false, true),
  ('Cao Lau', false, true),
  ('Mi Quang', false, true),
  ('Banh Xeo', false, true),
  ('Banh Cuon', false, true),
  ('Banh Khot', false, true),
  ('Bo La Lot', false, true),
  ('Goi Ga', false, true),

  -- Indian specifics
  ('Hyderabadi Biryani', false, true),
  ('Chettinad Chicken', false, true),
  ('Pepper Chicken', false, true),
  ('Saag Paneer', false, true),
  ('Malai Kofta', false, true),
  ('Paratha', false, true),
  ('Chapati', false, true),
  ('Aloo Paratha', false, true),
  ('Garlic Naan', false, true),
  ('Bhel Puri', false, true),
  ('Pani Puri', false, true),
  ('Dahi Puri', false, true),
  ('Aloo Tikki', false, true),
  ('Vada Pav', false, true),
  ('Dhokla', false, true),
  ('Misal Pav', false, true),
  ('Khaman', false, true),
  ('Kheer', false, true),
  ('Rasmalai', false, true),

  -- Indonesian / Malaysian / SE Asian
  ('Soto Ayam', false, true),
  ('Sate Ayam', false, true),
  ('Gado Gado', false, true),
  ('Bakso', false, true),
  ('Bubur Ayam', false, true),
  ('Roti Canai', false, true),
  ('Char Kway Teow', false, true),
  ('Cendol', false, true),
  ('Hokkien Mee', false, true),
  ('Pho Cuon', false, true),

  -- Filipino
  ('Sisig', false, true),
  ('Kare-kare', false, true),
  ('Pancit', false, true),
  ('Halo-Halo', false, true),
  ('Tocino', false, true),
  ('Longanisa', false, true),
  ('Lechon Kawali', false, true),
  ('Pork Adobo', false, true),
  ('Chicken Adobo', false, true),

  -- Middle Eastern / Levantine specifics
  ('Sabich', false, true),
  ('Mujadara', false, true),
  ('Kabsa', false, true),
  ('Mandi', false, true),
  ('Knafeh', false, true),
  ('Iskender Kebab', false, true),
  ('Sucuk', false, true),
  ('Cig Kofte', false, true),
  ('Imam Bayildi', false, true),
  ('Bourekas', false, true),
  ('Pastitsio', false, true),
  ('Stifado', false, true),
  ('Kleftiko', false, true),
  ('Avgolemono Soup', false, true),
  ('Saganaki', false, true),
  ('Loukoumades', false, true),

  -- Eastern European / Russian / Caucasus specifics
  ('Beef Stroganoff', false, true),
  ('Olivier Salad', false, true),
  ('Plov', false, true),
  ('Manti', false, true),
  ('Khinkali', false, true),
  ('Khachapuri', false, true),
  ('Pkhali', false, true),
  ('Lagman', false, true),
  ('Solyanka', false, true),

  -- French specifics
  ('Tartiflette', false, true),
  ('Flammekueche', false, true),
  ('Gratin Dauphinois', false, true),
  ('Tarte Flambée', false, true),
  ('Pissaladière', false, true),
  ('Aligot', false, true),
  ('Quenelles', false, true),
  ('Choucroute', false, true),
  ('Chateaubriand', false, true),
  ('Boudin Noir', false, true),
  ('Andouillette', false, true),
  ('Coulibiac', false, true),
  ('Pot-au-feu', false, true),
  ('Vichyssoise', false, true),

  -- Spanish / Iberian specifics
  ('Fideuà', false, true),
  ('Pulpo a la Gallega', false, true),
  ('Cocido Madrileño', false, true),
  ('Fabada Asturiana', false, true),
  ('Salmorejo', false, true),
  ('Gazpacho', false, true),

  -- British / Irish
  ('Shepherds Pie', false, true),
  ('Cottage Pie', false, true),
  ('Steak and Kidney Pie', false, true),
  ('Bangers and Mash', false, true),
  ('Yorkshire Pudding', false, true),
  ('Toad in the Hole', false, true),
  ('Beef Wellington', false, true),
  ('Cornish Pasty', false, true),
  ('Welsh Rarebit', false, true),
  ('Ploughmans Lunch', false, true),
  ('Cock-a-Leekie Soup', false, true),
  ('Cullen Skink', false, true),

  -- Latin American specifics
  ('Pollo a la Brasa', false, true),
  ('Vaca Frita', false, true),
  ('Ropa Vieja', false, true),
  ('Yuca Frita', false, true),
  ('Maduros', false, true),
  ('Bandeja Paisa', false, true),
  ('Sancocho', false, true),
  ('Ajiaco', false, true),
  ('Encebollado', false, true),
  ('Locro', false, true),
  ('Causa', false, true),
  ('Chicharrón', false, true),
  ('Tacu Tacu', false, true),
  ('Arroz Chaufa', false, true),
  ('Empanadas Salteñas', false, true),
  ('Choripán', false, true),
  ('Provoleta', false, true),
  ('Milanesa Napolitana', false, true),
  ('Pão de Queijo', false, true),
  ('Acarajé', false, true),
  ('Vatapá', false, true),
  ('Brigadeiro', false, true),

  -- Mexican deeper cuts
  ('Discada', false, true),
  ('Suadero', false, true),
  ('Salbutes', false, true),
  ('Panuchos', false, true),
  ('Marquesitas', false, true),
  ('Chilorio', false, true),
  ('Mixiote', false, true),
  ('Cazo de Pescado', false, true),

  -- African specifics
  ('Bobotie', false, true),
  ('Bunny Chow', false, true),
  ('Boerewors', false, true),
  ('Pap and Wors', false, true),
  ('Doro Wat', false, true),
  ('Egusi Soup', false, true),
  ('Pounded Yam', false, true),
  ('Fufu', false, true),
  ('Akara', false, true),
  ('Plantain Stew', false, true),

  -- More sandwiches & handhelds
  ('Smashburger', false, true),
  ('Italian Beef', false, true),
  ('Roast Beef Sandwich', false, true),
  ('Chicken Salad Sandwich', false, true),
  ('Egg Salad Sandwich', false, true),
  ('Tuna Melt', false, true),
  ('Patty Melt', false, true),
  ('Monte Cristo', false, true),
  ('Chicken Cutlet Sandwich', false, true),
  ('Meatball Sub', false, true),
  ('Pulled Pork Sandwich', false, true),

  -- Pizza-specific
  ('Margherita', false, true),

  -- More breakfast / eggs
  ('Dutch Baby', false, true),
  ('Crumpets', false, true),
  ('English Muffin', false, true),
  ('Quiche Lorraine', false, true),
  ('Corned Beef Hash', false, true),
  ('Belgian Waffle', false, true),
  ('Nutella Crepe', false, true),
  ('Soft Boiled Egg', false, true),
  ('Hard Boiled Egg', false, true),
  ('Poached Eggs', false, true),
  ('Sunny Side Up', false, true),
  ('Egg Salad', false, true),
  ('Deviled Eggs', false, true),
  ('Egg in a Hole', false, true),

  -- More salads
  ('Beet Salad', false, true),
  ('Spinach Salad', false, true),
  ('Watermelon Salad', false, true),
  ('Tabouli', false, true),
  ('Sashimi Salad', false, true),
  ('Beef Salad', false, true),
  ('Octopus Salad', false, true),
  ('Israeli Salad', false, true),
  ('Tomato Salad', false, true),
  ('Cucumber Salad', false, true),
  ('Bean Salad', false, true),
  ('Lentil Salad', false, true),
  ('Couscous Salad', false, true),

  -- More soups & stews
  ('Beef Stew', false, true),
  ('Lamb Stew', false, true),
  ('Pork Stew', false, true),
  ('Vegetable Soup', false, true),
  ('Lentil Soup', false, true),
  ('Black Bean Soup', false, true),
  ('Tomato Soup', false, true),
  ('Pumpkin Soup', false, true),
  ('Corn Chowder', false, true),
  ('Albondigas Soup', false, true),
  ('Sopa de Lima', false, true),

  -- More desserts
  ('Affogato', false, true),
  ('Croissant', false, true),
  ('Pain au Chocolat', false, true),
  ('Strudel', false, true),
  ('Eton Mess', false, true),
  ('Pavlova', false, true),
  ('Profiterole', false, true),
  ('Madeleine', false, true),
  ('Financier', false, true),
  ('Mille Crepe', false, true),
  ('Lava Cake', false, true),
  ('Banana Bread', false, true),
  ('Carrot Cake', false, true),
  ('Red Velvet Cake', false, true),
  ('Black Forest Cake', false, true),
  ('Sticky Rice Mango', false, true),
  ('Brownie Sundae', false, true),
  ('Donut', false, true),
  ('Cinnamon Roll', false, true),
  ('Beignet', false, true),
  ('Bibingka', false, true),

  -- More sides / starters
  ('Stuffed Grape Leaves', false, true),
  ('Edamame', false, true),
  ('Pickles Plate', false, true),
  ('Olive Plate', false, true),
  ('Cheese Plate', false, true),
  ('Charcuterie Board', false, true),
  ('Bread Basket', false, true),
  ('Veggie Crudités', false, true),
  ('Devilled Eggs', false, true),
  ('Stuffed Jalapeños', false, true),
  ('Polenta Fries', false, true),
  ('Yuca Fries', false, true),
  ('Curly Fries', false, true),
  ('Truffle Fries', false, true),

  -- Bowls / poke specifics
  ('Tuna Poke Bowl', false, true),
  ('Salmon Poke Bowl', false, true),
  ('Shrimp Bowl', false, true),
  ('Chicken Bowl', false, true),
  ('Tofu Bowl', false, true),
  ('Beef Bowl', false, true),
  ('Veggie Bowl', false, true),

  -- Tacos by filling
  ('Fish Taco', false, true),
  ('Shrimp Taco', false, true),
  ('Beef Taco', false, true),
  ('Chicken Taco', false, true),
  ('Pork Taco', false, true),
  ('Lamb Taco', false, true),
  ('Veggie Taco', false, true),

  -- Steak preparations
  ('Tomahawk', false, true),
  ('Filet Mignon', false, true),
  ('Ribeye Steak', false, true),
  ('Sirloin Steak', false, true),
  ('NY Strip', false, true),
  ('T-Bone Steak', false, true),
  ('Porterhouse', false, true),
  ('Hanger Steak', false, true),
  ('Skirt Steak', false, true),
  ('Wagyu Steak', false, true),

  -- Chicken-forward
  ('Chicken Katsu', false, true),
  ('Nashville Hot Chicken', false, true),
  ('Buffalo Wings', false, true),
  ('Honey Garlic Wings', false, true),
  ('Chicken Shawarma', false, true),
  ('Chicken Souvlaki', false, true),
  ('Chicken Schnitzel', false, true),

  -- Dumplings worldwide
  ('Pierogi Plate', false, true),
  ('Vareniki Plate', false, true),
  ('Wonton Plate', false, true),
  ('Soup Dumplings', false, true)
ON CONFLICT (name) DO NOTHING;
