/**
 * Tests for the token CSS variable generator output.
 *
 * Verifies that apps/web-portal/app/tokens.css was generated correctly
 * by packages/tokens/scripts/generate-css-vars.ts.
 */

import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

const tokensPath = resolve(__dirname, '../app/tokens.css');
const css = readFileSync(tokensPath, 'utf8');

describe('generate-css-vars output', () => {
  it('starts with the do-not-edit comment header', () => {
    expect(css).toMatch(/^\/\* DO NOT EDIT — generated by packages\/tokens\/scripts\/generate-css-vars\.ts \*\//);
  });

  it('wraps all variables in :root { }', () => {
    expect(css).toContain(':root {');
    expect(css).toContain('}');
  });

  it('converts hex colors to oklch format', () => {
    // Every --token-color-* value should use oklch(...)
    const colorLines = css
      .split('\n')
      .filter((l) => l.includes('--token-color-'));
    expect(colorLines.length).toBeGreaterThan(0);
    for (const line of colorLines) {
      expect(line).toMatch(/oklch\(/);
    }
  });

  it('converts #FF9800 (warning/accent) to an oklch value', () => {
    // #FF9800 is both colors.warning and colors.accent — should appear as oklch
    const warningLine = css.split('\n').find((l) => l.includes('--token-color-warning'));
    expect(warningLine).toBeDefined();
    expect(warningLine).toMatch(/oklch\(/);
    // Hue should be in the ~55–70° range (orange-yellow)
    const match = warningLine!.match(/oklch\(([\d.]+)\s+([\d.]+)\s+([\d.]+)\)/);
    expect(match).not.toBeNull();
    const hue = parseFloat(match![3]);
    expect(hue).toBeGreaterThan(50);
    expect(hue).toBeLessThan(80);
  });

  it('converts spacing.md (12px) to --token-space-md: 0.75rem', () => {
    expect(css).toContain('--token-space-md: 0.75rem;');
  });

  it('generates --token-space-card: 1.5rem (24px)', () => {
    expect(css).toContain('--token-space-card: 1.5rem;');
  });

  it('excludes React Native shadow properties (shadowColor, shadowOffset, elevation)', () => {
    expect(css).not.toContain('shadowColor');
    expect(css).not.toContain('shadowOffset');
    expect(css).not.toContain('elevation');
  });

  it('converts shadows to CSS box-shadow format', () => {
    expect(css).toContain('--token-shadow-sm: 0 1px 2px rgba(0,0,0,0.05);');
    expect(css).toContain('--token-shadow-base: 0 2px 4px rgba(0,0,0,0.1);');
    expect(css).toContain('--token-shadow-md: 0 4px 8px rgba(0,0,0,0.15);');
    expect(css).toContain('--token-shadow-lg: 0 8px 16px rgba(0,0,0,0.2);');
  });

  it('converts border-radius to rem (none → 0, full → 9999px)', () => {
    expect(css).toContain('--token-radius-none: 0;');
    expect(css).toContain('--token-radius-full: 9999px;');
    expect(css).toContain('--token-radius-sm: 0.25rem;');
  });

  it('generates typography size tokens in rem', () => {
    expect(css).toContain('--token-type-size-xs: 0.75rem;');
    expect(css).toContain('--token-type-size-base: 1rem;');
  });

  it('uses orange brand primary (not blue #007AFF)', () => {
    const primaryLine = css.split('\n').find((l) => l.match(/--token-color-primary:/));
    expect(primaryLine).toBeDefined();
    // Orange hue ~30–45°; the old blue #007AFF has hue ~260°
    const match = primaryLine!.match(/oklch\(([\d.]+)\s+([\d.]+)\s+([\d.]+)\)/);
    expect(match).not.toBeNull();
    const hue = parseFloat(match![3]);
    expect(hue).toBeGreaterThan(25);
    expect(hue).toBeLessThan(55);
  });
});
