#!/usr/bin/env tsx
/**
 * Generates CSS custom properties from @eatme/tokens JS values.
 *
 * Conversions:
 *   Colors   → hex → oklch via culori
 *   Spacing  → px  → rem (÷ 16)
 *   Typography sizes → px → rem
 *   Border radius    → px → rem (0 stays 0, 9999 stays 9999px)
 *   Shadows  → React Native format → CSS box-shadow (RN-only fields excluded)
 *
 * Output: apps/web-portal/app/tokens.css
 * Run:    pnpm --filter @eatme/tokens generate:css
 */

import { fileURLToPath } from 'node:url';
import * as fs from 'node:fs';
import * as path from 'node:path';
import { formatCss, oklch, parse } from 'culori';
import { colors, spacing, typography, borderRadius, shadows } from '../src/index';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

/** camelCase → kebab-case (e.g. primaryDark → primary-dark) */
function toKebab(key: string): string {
  return key.replace(/([A-Z])/g, (c) => `-${c.toLowerCase()}`);
}

/** Convert hex color string to an oklch(...) CSS value */
export function hexToOklch(hex: string): string {
  const parsed = parse(hex);
  if (!parsed) return hex;
  const ok = oklch(parsed);
  if (!ok) return hex;
  return formatCss(ok);
}

/** Convert a pixel number to a rem string */
export function pxToRem(px: number): string {
  return `${px / 16}rem`;
}

/** Build the full CSS string */
export function generate(): string {
  const lines: string[] = [
    '/* DO NOT EDIT — generated by packages/tokens/scripts/generate-css-vars.ts */',
    ':root {',
  ];

  // ── Colors: hex → oklch ────────────────────────────────────────────────
  for (const [key, value] of Object.entries(colors)) {
    if (typeof value === 'string' && value.startsWith('#')) {
      lines.push(`  --token-color-${toKebab(key)}: ${hexToOklch(value)};`);
    }
  }

  // ── Spacing: px → rem ──────────────────────────────────────────────────
  for (const [key, value] of Object.entries(spacing)) {
    if (key === 'unit') continue; // base unit constant, not a spacing step
    if (typeof value === 'number') {
      lines.push(`  --token-space-${key}: ${pxToRem(value)};`);
    }
  }

  // ── Typography sizes: px → rem ─────────────────────────────────────────
  for (const [key, value] of Object.entries(typography.size)) {
    if (typeof value === 'number') {
      lines.push(`  --token-type-size-${key}: ${pxToRem(value)};`);
    }
  }

  // ── Typography weights: output as-is ───────────────────────────────────
  for (const [key, value] of Object.entries(typography.weight)) {
    lines.push(`  --token-type-weight-${key}: ${value};`);
  }

  // ── Typography line heights: output as-is ──────────────────────────────
  for (const [key, value] of Object.entries(typography.lineHeight)) {
    lines.push(`  --token-type-leading-${key}: ${value};`);
  }

  // ── Border radius: px → rem ────────────────────────────────────────────
  for (const [key, value] of Object.entries(borderRadius)) {
    if (typeof value === 'number') {
      let out: string;
      if (value === 0) out = '0';
      else if (value >= 9999) out = '9999px'; // full/pill shape
      else out = pxToRem(value);
      lines.push(`  --token-radius-${key}: ${out};`);
    }
  }

  // ── Shadows: React Native → CSS box-shadow ─────────────────────────────
  // Excludes: shadowColor, shadowOffset.width, elevation (Android-only)
  for (const [key, shadow] of Object.entries(shadows)) {
    const s = shadow as {
      shadowColor: string;
      shadowOffset: { width: number; height: number };
      shadowOpacity: number;
      shadowRadius: number;
      elevation: number;
    };
    const y = s.shadowOffset.height;
    const blur = s.shadowRadius;
    const opacity = s.shadowOpacity;
    lines.push(`  --token-shadow-${key}: 0 ${y}px ${blur}px rgba(0,0,0,${opacity});`);
  }

  lines.push('}');
  return lines.join('\n') + '\n';
}

// ── Write output ───────────────────────────────────────────────────────────
const outputPath = path.resolve(__dirname, '../../../apps/web-portal/app/tokens.css');
fs.mkdirSync(path.dirname(outputPath), { recursive: true });
fs.writeFileSync(outputPath, generate(), 'utf8');
console.log(`Generated ${path.relative(process.cwd(), outputPath)}`);
