/**
 * DailyFilterModal constants
 */

// Full list used in the Meal Selection Modal
export const ALL_MEALS: string[] = [
  'Tacos',
  'Pizza',
  'Burger',
  'Pasta',
  'Sushi',
  'Salad',
  'Steak',
  'Ramen',
  'Sandwich',
  'Curry',
  'Burrito',
  'Noodles',
  'Rice Bowl',
  'Soup',
  'BBQ',
  'Wings',
  'Kebab',
  'Pho',
  'Pad Thai',
  'Dumplings',
  'Fried Chicken',
  'Falafel',
  'Gyros',
  'Quesadilla',
  'Nachos',
  'Tostadas',
  'Enchiladas',
  'Bento Box',
  'Bibimbap',
  'Paella',
  'Risotto',
  'Gnocchi',
  'Lasagna',
  'Fettuccine',
  'Poke Bowl',
  'Spring Rolls',
  'Tempura',
  'Udon',
  'Soba',
  'Biryani',
  'Tikka Masala',
  'Vindaloo',
  'Shawarma',
  'Schnitzel',
  'Fish & Chips',
  'Hot Dog',
  'Philly Cheesesteak',
  'Club Sandwich',
  'Banh Mi',
  'Croissant',
  'Bagel',
  'Pancakes',
  'Waffles',
  'Omelette',
  'Breakfast Burrito',
  'French Toast',
  'Eggs Benedict',
  'Huevos Rancheros',
  'Chilaquiles',
];
