/**
 * Database Types
 *
 * This file will be auto-generated by Supabase CLI using:
 * supabase gen types typescript --local > src/types.ts
 *
 * For now, we define a placeholder type that will be replaced.
 */

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

/**
 * Database schema types
 *
 * This will be auto-generated from your Supabase schema.
 * Currently using placeholder until schema is created.
 */
export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          email: string;
          created_at: string;
          profile_id: string | null;
        };
        Insert: {
          id?: string;
          email: string;
          created_at?: string;
          profile_id?: string | null;
        };
        Update: {
          id?: string;
          email?: string;
          created_at?: string;
          profile_id?: string | null;
        };
      };
      profiles: {
        Row: {
          id: string;
          display_name: string | null;
          avatar_url: string | null;
          reward_points: number;
          permanent_filters: Json | null;
          learned_preferences: Json | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          display_name?: string | null;
          avatar_url?: string | null;
          reward_points?: number;
          permanent_filters?: Json | null;
          learned_preferences?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          display_name?: string | null;
          avatar_url?: string | null;
          reward_points?: number;
          permanent_filters?: Json | null;
          learned_preferences?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      restaurants: {
        Row: {
          id: string;
          name: string;
          name_translations: Json | null;
          location: unknown; // PostGIS geography type
          address: string;
          address_translations: Json | null;
          country_code: string | null;
          city: string | null;
          cuisine_types: string[];
          price_level: number;
          rating: number | null;
          open_hours: Json | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          name_translations?: Json | null;
          location: unknown;
          address: string;
          address_translations?: Json | null;
          country_code?: string | null;
          city?: string | null;
          cuisine_types?: string[];
          price_level: number;
          rating?: number | null;
          open_hours?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          name_translations?: Json | null;
          location?: unknown;
          address?: string;
          address_translations?: Json | null;
          country_code?: string | null;
          city?: string | null;
          cuisine_types?: string[];
          price_level?: number;
          rating?: number | null;
          open_hours?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      dishes: {
        Row: {
          id: string;
          restaurant_id: string;
          name: string;
          name_translations: Json | null;
          description: string | null;
          description_translations: Json | null;
          price: number;
          calories: number | null;
          ingredients: string[];
          allergens: string[];
          dietary_tags: string[];
          spice_level: number | null;
          image_url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          restaurant_id: string;
          name: string;
          name_translations?: Json | null;
          description?: string | null;
          description_translations?: Json | null;
          price: number;
          calories?: number | null;
          ingredients?: string[];
          allergens?: string[];
          dietary_tags?: string[];
          spice_level?: number | null;
          image_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          restaurant_id?: string;
          name?: string;
          name_translations?: Json | null;
          description?: string | null;
          description_translations?: Json | null;
          price?: number;
          calories?: number | null;
          ingredients?: string[];
          allergens?: string[];
          dietary_tags?: string[];
          spice_level?: number | null;
          image_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      reviews: {
        Row: {
          id: string;
          user_id: string;
          subject_type: 'dish' | 'restaurant';
          subject_id: string;
          rating: number;
          text: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          subject_type: 'dish' | 'restaurant';
          subject_id: string;
          rating: number;
          text?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          subject_type?: 'dish' | 'restaurant';
          subject_id?: string;
          rating?: number;
          text?: string | null;
          created_at?: string;
        };
      };
      favorites: {
        Row: {
          id: string;
          user_id: string;
          subject_type: 'dish' | 'restaurant';
          subject_id: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          subject_type: 'dish' | 'restaurant';
          subject_id: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          subject_type?: 'dish' | 'restaurant';
          subject_id?: string;
          created_at?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      subject_type: 'dish' | 'restaurant';
    };
  };
}
